/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Process.MonHoc;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class frmCapNhatMonHoc extends javax.swing.JFrame {

    /**
     * Creates new form frmCapNhatMonHoc
     */
    private final MonHoc monHoc = new MonHoc();
    private final DefaultTableModel tableModel = new DefaultTableModel();
    private boolean isNew = true;

    public final void LoadDataCombo() {
        ResultSet result = null;
        try {
            result = monHoc.LoadBoMon();
            while (result.next()) {
                cbxBoMon.addItem(result.getString("MaBM"));
            }
        } catch (SQLException e) {
        }
    }

    public final void LoadDataTable() throws SQLException {
        ResultSet result = null;
        result = monHoc.LoadMonHoc();
        try {
            ClearDataTable();
            while (result.next()) {
                String rows[] = new String[4];
                rows[0] = result.getString(1);
                rows[1] = result.getString(2);
                rows[2] = result.getString(3);
                rows[3] = result.getString(5);
                tableModel.addRow(rows);
            }
        } catch (SQLException e) {
        }
    }

    private void setEmptyTextBox() {
        txtMaMH.setText(null);
        txtMaMH.requestFocus();
        txtTenMH.setText(null);
        txtSoTiet.setText(null);
        txtTenMH.setText(null);
    }

    private void lockTextBox(boolean e) {
        txtMaMH.setEnabled(!e);
        txtTenMH.setEnabled(!e);
        txtSoTiet.setEnabled(!e);
        cbxBoMon.setEnabled(!e);
        txtTenMH.setEnabled(!e);

    }

    private void enableButton(boolean e) {
        btnThem.setEnabled(e);
        btnXoa.setEnabled(e);
        btnSua.setEnabled(e);

        btnLuu.setEnabled(!e);
        btnKhongLuu.setEnabled(!e);
        btnThoat.setEnabled(e);
    }

    public void ClearDataTable() throws SQLException {
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);
        }
    }

    public frmCapNhatMonHoc() throws SQLException {
        initComponents();
        // Define table columns
        String[] colsName = {"Mã MH", "Tên Môn Học", "Số Tiết", " Mã BM"};
        tableModel.setColumnIdentifiers(colsName);
        jTableQLMH.setModel(tableModel);

        // Load data table
        LoadDataTable();

        // Load combobox BoMon
        LoadDataCombo();

        // set empty all textboxes
        setEmptyTextBox();

        // Dsiable all textboxes
        lockTextBox(true);

        // Enable some buttons and disable others
        enableButton(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnKhongLuu = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtMaMH = new javax.swing.JTextField();
        txtSoTiet = new javax.swing.JTextField();
        txtTenMH = new javax.swing.JTextField();
        cbxBoMon = new javax.swing.JComboBox<>();
        txtBoMon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableQLMH = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Quản Lý Môn Học");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã MH:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số Tiết:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tên MH:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Bộ Môn:");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnKhongLuu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKhongLuu.setText("K. Lưu");
        btnKhongLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhongLuuActionPerformed(evt);
            }
        });

        btnThoat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        txtMaMH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMHActionPerformed(evt);
            }
        });

        txtSoTiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtTenMH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbxBoMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxBoMon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBoMonItemStateChanged(evt);
            }
        });
        cbxBoMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBoMonActionPerformed(evt);
            }
        });

        txtBoMon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTableQLMH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableQLMH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã MH", "Tên Môn Học", "Số Tiết", "Mã BM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTableQLMH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableQLMHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableQLMH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThoat))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenMH)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnThem)
                                .addGap(50, 50, 50)
                                .addComponent(btnXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSua)
                                .addGap(27, 27, 27)
                                .addComponent(btnLuu)
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(txtSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(211, 211, 211)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnKhongLuu)
                            .addComponent(txtBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(txtMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtSoTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxBoMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnSua)
                    .addComponent(btnLuu)
                    .addComponent(btnKhongLuu)
                    .addComponent(btnThoat))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        // TODO add your handling code here:
        String maMH = txtMaMH.getText();
        String tenMH = txtTenMH.getText();
        int soTiet = Integer.parseInt(txtSoTiet.getText());
        String maBM = cbxBoMon.getSelectedItem().toString();
        if (maMH.length() == 0 || tenMH.length() == 0 || soTiet == 0 || maBM.length() == 0) {
            JOptionPane.showMessageDialog(null,
                    "Vui long nhap day du thong tin!", "Thong bao", 1);
        } else if (maMH.length() > 4 || tenMH.length() > 100 || maBM.length() > 4 || soTiet <= 0) {
            JOptionPane.showMessageDialog(null,
                    "Qua so ky tu quy dinh. Vui long nhap lai!", "Thong bao", 1);
        } else {
            try {
                if (isNew == true) //Luu cho tthem moi
                {
                    monHoc.InsertMonHoc(maMH, tenMH, soTiet, maBM);
                } else //Luu cho sua
                {
                    monHoc.EditMonHoc(maMH, tenMH, soTiet, maBM);
                }
                ClearDataTable();
                LoadDataTable();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Cap nhat that bai",
                        "Thong bao", 1);
            }
            lockTextBox(false);
            enableButton(true);
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnKhongLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhongLuuActionPerformed
        // TODO add your handling code here:
        setEmptyTextBox();
        lockTextBox(true);
        enableButton(true);
    }//GEN-LAST:event_btnKhongLuuActionPerformed

    private void txtMaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMHActionPerformed

    private void cbxBoMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBoMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBoMonActionPerformed

    private void jTableQLMHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableQLMHMouseClicked
        // TODO add your handling code here:
        try {
            int row = jTableQLMH.getSelectedRow();
            String maMH = (jTableQLMH.getModel().getValueAt(row, 0)).toString();
            ResultSet rs = monHoc.LoadMonHoc(maMH);
            if (rs.next()) {
                txtMaMH.setText(rs.getString("MaMH"));
                txtTenMH.setText(rs.getString("TenMH"));
                txtSoTiet.setText(rs.getString("SoTiet"));
                cbxBoMon.setSelectedItem(rs.getString("MaBM"));
                txtBoMon.setText(rs.getString("TenBM"));
            }
        } catch (SQLException e) {
        }

    }//GEN-LAST:event_jTableQLMHMouseClicked

    private void cbxBoMonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBoMonItemStateChanged
        // TODO add your handling code here
        try {
            String maBM = cbxBoMon.getSelectedItem().toString();
            ResultSet result = monHoc.LoadBoMon(maBM);
            if (result.next()) {
                txtBoMon.setText(result.getString("TenBM"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCapNhatMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxBoMonItemStateChanged

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        String maMH = txtMaMH.getText();
        try {
            if (maMH.length() == 0) {
                JOptionPane.showMessageDialog(null, "Can chon 1 mon hoc de xoa", "Thong bao", 1);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Ban muon xoa mon hoc " + maMH
                        + " nay hay khong?", "Thong bao", 2) == 0) {
                    monHoc.DeleteMonHoc(maMH);
                    ClearDataTable();
                    LoadDataTable();
                    setEmptyTextBox();
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCapNhatMonHoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        setEmptyTextBox();
        lockTextBox(false);
        enableButton(false);
        isNew = true;
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        String maMH = txtMaMH.getText();
        if (maMH.length() == 0) {
            JOptionPane.showMessageDialog(null, "Vui long chon loi can sua",
                    "Thong Bao", 1);
        } else {
            lockTextBox(false);
            enableButton(false);
            isNew = false;
            txtMaMH.setEnabled(false);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        frmCapNhatMonHoc f = new frmCapNhatMonHoc();
        f.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKhongLuu;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbxBoMon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableQLMH;
    private javax.swing.JTextField txtBoMon;
    private javax.swing.JTextField txtMaMH;
    private javax.swing.JTextField txtSoTiet;
    private javax.swing.JTextField txtTenMH;
    // End of variables declaration//GEN-END:variables
}
